<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogArticleRepository extends EntityRepository
{
}
